
#ifndef DEFINES_HPP
# define DEFINES_HPP

# define MIN_PORT 1024
# define MAX_PORT 65535
# define DELIMITER "\r\n"
# define ERR_UNKNOWNCOMMAND 421
# define ERR_ERRONEUSNICKNAME 432
# define ERR_NICKNAMEINUSE 433
# define ERR_NOTREGISTERED 451
# define ERR_NEEDMOREPARAMS 461
# define ERR_PASSWDMISMATCH 464
# define RPL_WELCOME 001
# define RPL_YOURHOST 002
# define RPL_NOTOPIC 331
# define RPL_TOPIC 332
# define RPL_NAMREPLY 353
# define RPL_ENDOFNAMES 366
# define ERR_NOSUCHNICK 401
#define ERR_NOSUCHCHANNEL 403
#define ERR_NOTONCHANNEL 442
#define ERR_USERNOTINCHANNEL 441
#define ERR_CHANOPRIVSNEEDED 482
# define ERR_PORT_RANGE "Given port is out of the program's valid range, please try another port!"

#endif